apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-test
  labels: 
    app.kubernetes.io/name: api-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-test
    spec:
      containers:
      - image: andremuzel/api-test:latest
        name: api-test
        ports:
          - containerPort : 5000
            name: http
        volumeMounts:
          - name: resolv-conf
            mountPath: /etc/resolv.conf
      volumes:
        - name: resolv-conf
          hostPath:
            path: /etc/resolv.conf  
            type: File



      
