apiVersion: v1
kind: Service
metadata:
  name: api-test
  labels:
    app.kubernetes.io/name: api-test
spec:
  selector:
    app.kubernetes.io/name: api-test
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 30085
